### ISSUE TITLE
Reproducible on different machines?

### ISSUE THREAD

**Issue by wcornwell** [daniel1noble/evolplasticty#3]
Try knitting the Rmd file and see if that works on your system? I messed around with the relative paths a bit.

**Comment by daniel1noble** [comment]
Cool! Will check now.

**Comment by daniel1noble** [comment]
All good. Renders properly. Thanks for re-writing the last bit of code! I already had that directory on my end, but it's find to have it in. Thanks for .gitignore to. We can update that baby on Friday!
